# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "rails_locale_detection"
  s.version = "1.3.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mateo Murphy"]
  s.date = "2013-03-19"
  s.description = "Sets the current locale of a request using a combination of params, cookies, and http headers"
  s.email = "mateo.murphy@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = `git ls-files`.split($/)
  s.homepage = "http://github.com/mateomurphy/rails_locale_detection"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "locale setting for rails project"

  s.add_dependency 'rails', '~> 3.2.13'
  s.add_dependency 'i18n'
  s.add_dependency 'http_accept_language'

  s.add_development_dependency(%q<timecop>)
  s.add_development_dependency(%q<rspec>, ["~> 2.12.0"])
  s.add_development_dependency(%q<bundler>, ["~> 1.3.4"])
  s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
end